### ISSUE TITLE
[rootless] `podman ps` doesn't show anything, even though container is running (started by systemd service)

### ISSUE THREAD

**Issue by AdrianKoshka** [containers/libpod#1680]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] **kind bug**

**Description**

I have a systemd service, which is `enable`d, it starts a rootless container. If I ssh into the machine and run `podman ps`, I get no output, like the container isn't running. If I do `systemctl status unifi`, I can clearly see the container _is_ running.

**Steps to reproduce the issue:**

1. create a systemd service to start a container, e.g.:

```
	[Unit]
	Description=UniFi Container
	After=network-online.target
	

	[Service]
	Type=simple
	User=alc
	Group=alc
	ExecStart=/usr/bin/podman start -a unifi-sdn-controller
	ExecStop=/usr/bin/podman stop unifi-sdn-controller
	

	[Install]
	WantedBy=multi-user.target
```

2. `systemctl enable foobarcontainer.service`

3. reboot

4. ssh or login at a terminal, and run `podman ps`, notice it acts as if the container isn't running.

5. `systemctl status foobarcontainer.service` shows it obviously is.

**Describe the results you received:**

`podman ps` has no output

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.9.3.1
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.3.1-1.git1cd906d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 3c91f791086f31a0bd68967c7e3c2ad8e06145a6-dirty'
  MemFree: 197369856
  MemTotal: 2077790208
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 2211151872
  SwapTotal: 2214588416
  arch: amd64
  cpus: 2
  hostname: atomic.ccbp.online
  kernel: 4.18.11-200.fc28.x86_64
  os: linux
  uptime: 223h 38m 0.68s (Approximately 9.29 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /var/home/alc/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora Atomic Host 28

**Comment by giuseppe** [comment]
I think this depends on `/run/user/UID` not existing, could you check if there is anything under `$HOME/rundir`?  That is the fallback location when `/run/user/UID` is not writeable.

**Comment by TomSweeneyRedHat** [comment]
And I'm just curious, does `podman ps --all` show the container?  You shouldn't need the --all, but it would be a good data point to have.

**Comment by mheon** [comment]
I suspect this is as @giuseppe said. We check `/run/usr/UID` for some of our state, which I don't think is created when a systemd service runs.

@giuseppe Could we write a file somewhere in the user's homedir containing the root and runroot we used to start rootless podman, to try and catch scenarios like this?

**Comment by AdrianKoshka** [comment]
@TomSweeneyRedHat It's there if you do a `--all`, just not shown as active.

**Comment by AdrianKoshka** [comment]
`/run/user/1000/` exists, but not `$HOME/rundir`.

**Comment by TomSweeneyRedHat** [comment]
@AdrianKoshka thanks muchly for the follow up.  I too think @giuseppe is on the right track, but it's nice to know that --all turns the container up.

**Comment by mheon** [comment]
I think we're running into something similar to what the Openstack folks were when they tried Podman in a container - we end up with a different rundir, so we don't have an alive file. Without the alive file, we assume the system has restarted, so we clear the state, which makes us lose the running container's PID and believe it is stopped.

**Comment by rhatdan** [comment]
Is systemd running with a different /run then on the host?

**Comment by mheon** [comment]
@rhatdan I think /run/user won't exist (only created when a user logs in, I don't think systemd units count)

**Comment by mheon** [comment]
We might want to move it by default into somewhere in /tmp, so it doesn't disappear when the user logs out, and we don't have this issue

**Comment by rhatdan** [comment]
I would guess we can move the content to /tmp, but we need to be very careful to make sure these are not easily guessable paths, since other users could screw around with it.  If we are going to keep it permanently then putting it in ~/run directory might make more sense.  At least there it is protected from other users.

I am wondering if the /run/user still exists but in a different mount namespace, which is why you don't see it.

**Comment by mheon** [comment]
We do need it to be on a tmpfs to detect system restart - can nonroot users make a tmpfs in their own homedir? I don't think so, but I've never tried

**Comment by rhatdan** [comment]
You can within a user namespace.

**Comment by vrothberg** [comment]
@rhatdan, @mheon, let's revive this thread. I think moving it the path to `~/run` is the preferable solution. I am convinced, that moving it to `/tmp` will be considered as a security issue by some folks.

**Comment by rhatdan** [comment]
Probably should be .local/run

**Comment by rhatdan** [comment]
Or if we want to keep it private to containers it should go in 
~/local/containers/run

**Comment by mheon** [comment]
We probably want that to be a tmpfs, if the user namespace Podman rootless
makes will let us do that.

**Comment by rhatdan** [comment]
@mheon @giuseppe Whats happening with this issue?

**Comment by mheon** [comment]
This should be fixed by the code to reuse paths from the DB - we are now guaranteed that we won't swap tmp directories after Podman first starts.

**Comment by derkoe** [comment]
What version includes the fix? Just tried the same with the current RHEL 7.6 and it still does not work.

    [0][QA][root@artifactory01q:~] podman version
    Version:       0.12.1.2
    Go Version:    go1.10.3
    OS/Arch:       linux/amd64

**Comment by tobwen** [comment]
@derkoe This might not be helpful, but _podman_ is at v1.2.0 now. v0.12.1.2 is pretty outdated. Most of the rootless bugfixes have been added after release v1.0.

```
$ podman version
INFO[0000] running as rootless
Version:            1.3.0-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         fd39849beef3cdc6cce08814aaa1e12f60b37951
Built:              Thu Apr  4
```

**Comment by mheon** [comment]
Rootless won't be supported until 7.7, where we'll probably be shipping a 1.2.x release which includes this fix (amongst other package changes required to shadowutils)

**Comment by rhatdan** [comment]
1.0 release should be in 7.6.4, and should work better in rootless mode.

**Comment by derkoe** [comment]
We've got redhat-release-server-7.6-4.el7.x86_64 but still podman 0.12.1.2. 

There seem to be other bugs with this version like running with "-u username" results in "unable to find user username: no matching entries in passwd file" event though the user is in the passwd file.

Is it possible to install v1.2.0 on RHEL 7.6?

Otherwise we'll have to wait for 7.7.

**Comment by rhatdan** [comment]
Yes podman 1.2 should work fine on RHEL7.6.

**Comment by LucaCappelletti94** [comment]
I am facing the very same issue on `podman version 1.0.2-dev`.

**Comment by LucaCappelletti94** [comment]
I have resolved the issue: the podman instance has been launched using a custom run_root and root parameter. Using the following has displayed the correct output from ps:

```bash
podman --runroot=/my/path/goes/here --root=/my/path/goes/here ps
```

**Comment by developedsoftware** [comment]
Just had a very similar thing happen. podman ps --all showed no running containers but the service was up. Very strange!

**Comment by developedsoftware** [comment]
Is there a permanent solution to this? I am getting the same issue in podman version 2.0.5

I can use "podman --runroot=/my/path/goes/here --root=/my/path/goes/here" but wondering if this should even still be a problem? 

I am also starting podman services via a systemd service...

**Comment by mheon** [comment]
You are almost certainly seeing a different issue. This has been resolved for two years at this point. Please file a new issue.

**Comment by mheon** [comment]
Also, when you do, please include the unit file you're using.

**Comment by tazihad** [comment]
I have this problem in Fedora Silverblue 37. podman version 4.3.0. I don't see anything with `podman ps`. but `podman ps --all` works.

**Comment by alex27riva** [comment]
Hi everyone, I have the same issue on Debian 11 after creating the container with Ansible.
The container is running but is not showing either with `podman ps` or `podman  ps -all`.
