### ISSUE TITLE
Error running container in container created by podman

### ISSUE THREAD

**Issue by q384566678** [containers/libpod#2409]
/kind bug

**Description**

After creating a container with `podman`, running the container with `buildah` in the container will fail, but after I created the container with docker, I can run the container successfully.

**Steps to reproduce the issue:**

1.Start the container with podman
```
⚡ root@localhost  podman run -it --rm --cap-add=SYS_ADMIN --security-opt seccomp=unconfined 5619d44119b4 /bin/bash
```

2. Run the container using buildah inside the container.
```
root@4783ab8723ea:/# buildah bud --isolation chroot .         
```                                                                                                                          
**Describe the results you received:**
```
STEP 1: FROM busybox                                                                                                                                                                    
Getting image source signatures                                                                                                                                                         
Copying blob sha256:697743189b6d255069caf6c455be10c7f8cae8076c6f94d224ae15cd41420e87
 738.18 KiB / 738.18 KiB [==================================================] 3s
Copying config sha256:d8233ab899d419c58cf3634c0df54ff5d8acc28f8173f09c21df4a07229e1205
 1.46 KiB / 1.46 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: RUN "ls"
error running subprocess: error bind mounting /sys from host into mount namespace: permission denied
                                                                                                    error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin$
/sbin:/bin] Command:run Args:["ls"] Flags:[] Attrs:map[] Message:RUN "ls" Original:RUN "ls"}: exit status 1
```

**Describe the results you expected:**
It can run successfully like using docker.
```
⚡ root@localhost  docker run -it --rm --cap-add=SYS_ADMIN --security-opt seccomp=unconfined 5619d44119b4 /bin/bash
root@9678ff5c09be:/# buildah bud --isolation chroot .
STEP 1: FROM busybox
STEP 2: RUN "ls"
bin   dev   etc   home  proc  root  sys   tmp   usr   var
STEP 3: COMMIT containers-storage:[vfs@/var/lib/containers/storage+/var/run/containers/storage:vfs.override_kernel_check=true]@
b132099ac11497602b8805d630d33e1e50a7308ff64721fa38a8e2f84ad0a79e
Getting image source signatures
Skipping fetch of repeat blob sha256:adab5d09ba79ecf30d3a5af58394b23a447eda7ffffe16c500ddc5ccb4c0222f
Copying blob sha256:6cc6e74a6528af539095c73cc6ff18d2c84aed749987d100c6ce3b8b495c8887
 180 B / 180 B [============================================================] 0s
Copying config sha256:35bdae93cbfab4c95c85ae7efcda66025b671bccbe59b8a2b84466b85eebc1ff
 694 B / 694 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
--> b132099ac11497602b8805d630d33e1e50a7308ff64721fa38a8e2f84ad0a79e
root@9678ff5c09be:/#
```

**Output of `podman version`:**
```
Version:            1.0.1-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         3b88c7350726f5a019f989a1ab7e5046917f2f79
Built:              Fri Feb 22 03:14:01 2019
OS/Arch:            linux/amd64
```

**Output of `podman info`:**

```
host:                                                                                                                                                                                   
  BuildahVersion: 1.7-dev                                                                                                                                                               
  Conmon:                                                                                                                                                                               
    package: Unknown                                                                                                                                                                    
    path: /usr/libexec/podman/conmon                                                                                                                                                    
    version: 'conmon version 1.14.0-dev, commit: d89cc410f42f2ce9cd061b0db24417108f2794fe'                                                                                              
  Distribution:                                                                                                                                                                         
    distribution: '"centos"'                                                                                                                                                            
    version: "7"                                                                                                                                                                        
  MemFree: 1174769664                                                                                                                                                                   
  MemTotal: 2090246144                                                                                                                                                                  
  OCIRuntime:                                                                                                                                                                           
    package: containerd.io-1.2.2-3.3.el7.x86_64                                                                                                                                         
    path: /usr/sbin/runc                                                                                                                                                                
    version: |-                                                                                                                                                                         
      runc version 1.0.0-rc6+dev                                                                                                                                                        
      commit: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec                                                                                                                                  
      spec: 1.0.1-dev   
  SwapFree: 2140127232
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.20.11-1.el7.elrepo.x86_64
  os: linux
  rootless: false
  uptime: 13m 55.7s
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage

```
Tips: The same error can occur with the latest version of `buildah`.

**Comment by rhatdan** [comment]
Any chance this is an SELinux issue?

Could you try it setenforce 0

If it is, could you grab the SELinux error messages

ausearch -m AVC -ts recent

**Comment by mheon** [comment]
Might also be missing capabilities - we might need SYS_MOUNT in addition to
others... I'd try adding all caps and seeing if that fixes it

**Comment by rhatdan** [comment]
SYS_MOUNT is not a capability (I wish it was)  SYS_ADMIN controls mounts.

**Comment by q384566678** [comment]
> Could you try it setenforce 0
If it is, could you grab the SELinux error messages
ausearch -m AVC -ts recent

Here is SELinux error messages when setenforce 0:
```
 ⚡ root@localhost  ausearch -m AVC -ts recent
----
time->Mon Feb 25 00:12:20 2019
type=PROCTITLE msg=audit(1551071540.614:1716): proctitle="buildah-chroot-runtime"
type=SYSCALL msg=audit(1551071540.614:1716): arch=c000003e syscall=165 success=yes exit=0 a0=c420025a00 a1=c4203e03c0 a2=c420023540 a3=45004 items=0 ppid=22793 pid=22830 auid=0 uid=0 $
id=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=2 comm="exe" exe="/usr/local/bin/buildah" subj=system_u:system_r:container_t:s0:c3,c283 key=(null)
type=AVC msg=audit(1551071540.614:1716): avc:  denied  { mounton } for  pid=22830 comm="exe" path="/tmp/buildah823386363/mnt/rootfs/etc/hosts" dev="overlay" ino=129226 scontext=system$
u:system_r:container_t:s0:c3,c283 tcontext=system_u:object_r:container_file_t:s0:c3,c283 tclass=file permissive=1
----
time->Mon Feb 25 00:12:20 2019
type=PROCTITLE msg=audit(1551071540.614:1715): proctitle="buildah-chroot-runtime"
type=SYSCALL msg=audit(1551071540.614:1715): arch=c000003e syscall=165 success=yes exit=0 a0=c420025520 a1=c4201b0940 a2=c4200234e0 a3=4500f items=0 ppid=22793 pid=22830 auid=0 uid=0 $
id=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=2 comm="exe" exe="/usr/local/bin/buildah" subj=system_u:system_r:container_t:s0:c3,c283 key=(null)
type=AVC msg=audit(1551071540.614:1715): avc:  denied  { mounton } for  pid=22830 comm="exe" path="/tmp/buildah823386363/mnt/rootfs/sys/fs/cgroup/systemd" dev="cgroup" ino=3533 sconte$
t=system_u:system_r:container_t:s0:c3,c283 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=1
```

**Comment by giuseppe** [comment]
yes, confirmed it is SElinux blocking it.  For me it blocks the same mount also with Docker

**Comment by rhatdan** [comment]
I can easily allow the mounton for container_file_t, I am not crazy about the mounton for cgroup_t.  Any idea what is causing this?

**Comment by rhatdan** [comment]
Fixed in container-selinux-2.83-1.gitec6fcad

**Comment by rhatdan** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2019-f1c9724b22 
is available for Fedora 29

**Comment by q384566678** [comment]
I updated the selinux to 2.83 version under the fedora system, and the same error will still occur.

```
➜  ~ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31
➜  ~ podman run -it --rm --cap-add=SYS_ADMIN --security-opt seccomp=unconfined 5619d44119b4 /bin/bash
root@b71fb77d624d:/# vim Dockerfile
root@b71fb77d624d:/# buildah bud --isolation chroot .
STEP 1: FROM busybox
Getting image source signatures
Copying blob sha256:697743189b6d255069caf6c455be10c7f8cae8076c6f94d224ae15cd41420e87
 738.18 KiB / 738.18 KiB [==================================================] 6s
Copying config sha256:d8233ab899d419c58cf3634c0df54ff5d8acc28f8173f09c21df4a07229e1205
 1.46 KiB / 1.46 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: RUN "ls"
error running subprocess: error bind mounting /sys from host into mount namespace: permission denied
                                                                                                    error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:["ls"] Flags:[] Attrs:map[] Message:RUN "ls" Original:RUN "ls"}: exit status 1
root@b71fb77d624d:/# exit
exit
➜  ~ rpm -q container-selinux
container-selinux-2.83-1.gitec6fcad.fc28.noarch
```

**Comment by rhatdan** [comment]
New AVCs?

**Comment by q384566678** [comment]
No error messages when setenforce 0.
```
➜  ~ ausearch -m AVC -ts recent
<no matches>
```

**Comment by rhatdan** [comment]
And with setenforce 0 it works?

If yes then try to turn off Dontauditrules.
# semodule -DB
Run the container
Collect the new AVCs
Turn back on dontaudit rules.
# semodule -B

**Comment by q384566678** [comment]
> And with setenforce 0 it works?

Yes, After setenforce 0 can run successfully.

Thanks for your suggestion, here is the error message obtained:
```
time->Wed Feb 27 20:40:05 2019
type=AVC msg=audit(1551318005.701:488): avc:  denied  { mounton } for  pid=2526 comm="exe" path="/tmp/buildah471014920/mnt/rootfs/sys" dev="sysfs" ino=1 scontext=system_u:system_r:container_t:s0:c122,c213 tcontext=system_u:object_r:sysfs_t:s0 tclass=dir permissive=1
----
time->Wed Feb 27 20:40:05 2019
type=AVC msg=audit(1551318005.733:489): avc:  denied  { unmount } for  pid=2526 comm="exe" scontext=system_u:system_r:container_t:s0:c122,c213 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1

```

**Comment by rhatdan** [comment]
rpm -q container-selinux
container-selinux-2.83-1.gitec6fcad.fc29.noarch

**Comment by rhatdan** [comment]
I am building container-selinux-2.84-1.giteb60838.fc29

**Comment by rhatdan** [comment]
Could you try this on Fedora and make sure it works.

https://bodhi.fedoraproject.org/updates/FEDORA-2019-a775defd12

I have asked the packaging guys to package up a new version for RHEL7.

**Comment by q384566678** [comment]
After updating to version 2.84, this problem has been solved. Thank you!

I still have a question I would like to ask. After I updated selinux, I use podman to start a non-privileged container , and then I can use buildah to run the container directly in the container.
```
 ⚡ root@fedora29 ~ setenforce 1
 ⚡ root@fedora29 ~ podman run --rm -it ef61f7c099aa
root@50c1f27c6e94:/# buildah run --isolation chroot e347518ada21 ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
root@50c1f27c6e94:/# 
```
So is this the correct phenomenon? I remember that I need to add `CAP_SYS_ADMIN` capability when testing on other systems(Just like the examples above).

**Comment by rhatdan** [comment]
Right the whole goal of this is to get to the point that we can run buildah inside of a container without SYS_ADMIN privs.

@giuseppe PTAL

**Comment by rhatdan** [comment]
@q384566678 @giuseppe was trying to do this also and actually found another SELinux issue, which is fixed in container-selinux-2.85.  
But @giuseppe found that he had to disable seccomp filtering.  I think the unshare syscall was blocked.

**Comment by giuseppe** [comment]
>  But @giuseppe found that he had to disable seccomp filtering. I think the unshare syscall was blocked.

it seems that seccomp is disabling `pivot_root` and `mount` that we use.  If I create a custom file with these two syscalls enabled then it works fine

**Comment by rhatdan** [comment]
I thought we left mount enabled.  mount syscall is valid for some non SYS_ADMIN privs and should be allowed.  Docker never understood this.  Not sure pivot_root is a huge risk either.

**Comment by rhatdan** [comment]
I see mount in seccomp.json?
 grep mount /usr/share/containers/seccomp.json 
				"mount",
				"umount2",
				"mount",
				"umount",
				"umount2",

**Comment by giuseppe** [comment]
pivot_root should not be a big risk, it is valid only for the namespace it is running within

**Comment by rhatdan** [comment]
Do you have a seccomp.json file with it added?  I an beginning to work on a new skopeo release, that we could add it to.

**Comment by giuseppe** [comment]
sorry, there is no need to modify anything, I've just verified on a fresh install, the default seccomp profile and the updated SELinux policy are enough.

**Comment by q384566678** [comment]
Here is the test I did under the centos7 system:
I upgraded container-selinux to the latest version (currently the latest version of the centos system I can find is 2.84-2.el7.noarch).
```
 ⚡ root@centos7~ rpm -q container-selinux
container-selinux-2.84-2.el7.noarch
```
I tested it in the same way and found that the previous problem still occurred. It should be the latest version of the container-selinux under the centos system has not been released.
```
 ⚡ root@centos7~ podman run -it --rm ef61f7c099aa /bin/bash
root@a214a3da8465:/# buildah run --isolation chroot 2023fb236d37 ls
error running subprocess: error bind mounting /sys from host into mount namespace: permission denied
                                                                                                    ERRO[0000] exit status 1                                


```
Here is SELinux error messages when setenforce 0:
```
time->Sat Mar  2 01:11:21 2019
type=PROCTITLE msg=audit(1551507081.116:943): proctitle="buildah-chroot-runtime"
type=SYSCALL msg=audit(1551507081.116:943): arch=c000003e syscall=165 success=yes exit=0 a0=c420037ec0 a1=c4201fc5c0 a2=c4201fbf40 a3=4500f items=0 ppid=13469 pid=13502 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=1 comm="5" exe=2F6D656D66643A6275696C6461682D6368726F6F742D72756E74696D65202864656C6574656429 subj=system_u:system_r:container_t:s0:c172,c360 key=(null)
type=AVC msg=audit(1551507081.116:943): avc:  denied  { mounton } for  pid=13502 comm="5" path="/tmp/buildah377680961/mnt/rootfs/sys/fs/cgroup/systemd" dev="cgroup" ino=1803 scontext=system_u:system_r:container_t:s0:c172,c360 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=1
```

**Comment by rhatdan** [comment]
Fixes are in upstream.

If you checkout the https://github.com/containers/container-selinux repo.
You need to get the RHEL7.5 branch

git clone https://github.com/containers/container-selinux 
git pull --all
git checkout RHEL7.5
make
sudo semodule -i container.pp

Now see if it works?

**Comment by q384566678** [comment]
No, the same error will still occur:

```
 ⚡ root@centos7 ~/container-selinux  RHEL7.5 semodule -i container.pp.bz2
libsemanage.semanage_direct_install_info: Overriding container module at lower priority 200 with module at priority 400.
⚡ root@centos7 podman run -it --rm ef61f7c099aa /bin/bash
root@46ef0ec07b4b:/# buildah images
root@46ef0ec07b4b:/# buildah bud --isolation chroot .
STEP 1: FROM busybox
Getting image source signatures
Copying blob 697743189b6d [======================================] 738.2KiB / 738.2KiB
Copying config d8233ab899 [======================================] 1.5KiB / 1.5KiB
Writing manifest to image destination
Storing signatures
STEP 2: RUN "ls"
error running subprocess: error bind mounting /sys from host into mount namespace: permission denied
                                                                                                    error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:["ls"] Flags:[] Attrs:map[] Message:RUN "ls" Original:RUN "ls"}: exit status 1
ERRO[0013] exit status 1                                
root@46ef0ec07b4b:/# 
```

**Comment by giuseppe** [comment]
this is different than the error I was seeing.  Didn't it work for you earlier?  Is the selinux update the only difference now?

**Comment by q384566678** [comment]
I just updated the container-selinux and then performed the same test, and the error confidence that I showed was the [same as](https://github.com/containers/libpod/issues/2409#issuecomment-468890360) I did not update before.

**Comment by rhatdan** [comment]
@q384566678 I don;t understand the last comment.  Are you still seeing the issue or not?  What version of container-selinux have you installed?

**Comment by q384566678** [comment]
Ok, maybe my description is not clear.
First of all, I installed the latest container-selinux under the centos system.
```
 ⚡ root@centos7 rpm -q container-selinux
container-selinux-2.84-2.el7.noarch
```
Then I manually updated the container-selinux according to this [method](https://github.com/containers/libpod/issues/2409#issuecomment-469088747).
```
 ⚡ root@centos7 ~/container-selinux(RHEL7.5) git pull --all
Fetching origin                          
Already up-to-date.
 ⚡ root@centos7 ~/container-selinux(RHEL7.5) make
make -f /usr/share/selinux/devel/Makefile container.pp
make[1]: Entering directory `/root/container-selinux'
Compiling targeted container module
/usr/bin/checkmodule:  loading policy configuration from tmp/container.tmp
/usr/bin/checkmodule:  policy configuration loaded
/usr/bin/checkmodule:  writing binary representation (version 19) to tmp/container.mod
Creating targeted container.pp policy package
rm tmp/container.mod tmp/container.mod.fc
make[1]: Leaving directory `/root/container-selinux'
Compressing container.pp -> container.pp.bz2
bzip2 -9 container.pp
 ⚡ root@centos7 ~/container-selinux(RHEL7.5)  semodule -i container.pp.bz2
```
After the SElinux was set to enforcing, the following tests were performed:
```
⚡ root@centos7 podman run -it --rm ef61f7c099aa /bin/bash
root@46ef0ec07b4b:/# buildah images
root@46ef0ec07b4b:/# buildah bud --isolation chroot .
STEP 1: FROM busybox
Getting image source signatures
Copying blob 697743189b6d [======================================] 738.2KiB / 738.2KiB
Copying config d8233ab899 [======================================] 1.5KiB / 1.5KiB
Writing manifest to image destination
Storing signatures
STEP 2: RUN "ls"
error running subprocess: error bind mounting /sys from host into mount namespace: permission denied
                                                                                                    error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:["ls"] Flags:[] Attrs:map[] Message:RUN "ls" Original:RUN "ls"}: exit status 1
ERRO[0013] exit status 1                                
root@46ef0ec07b4b:/# 
```
From the above test, it can be seen that an error occurred while building the container in buildah.

**Comment by rhatdan** [comment]
Please attach the latest avc's

**Comment by q384566678** [comment]
```
----
time->Tue Mar  5 21:27:07 2019
type=PROCTITLE msg=audit(1551839227.325:653): proctitle="buildah-chroot-runtime"
type=SYSCALL msg=audit(1551839227.325:653): arch=c000003e syscall=165 success=no exit=-13 a0=c420037ec0 a1=c4201fc5c0 a2=c4201fbf50 a3=4500f items=0 ppid=13443 pid=13476 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=2 comm="5" exe=2F6D656D66643A6275696C6461682D6368726F6F742D72756E74696D65202864656C6574656429 subj=system_u:system_r:container_t:s0:c131,c995 key=(null)
type=AVC msg=audit(1551839227.325:653): avc:  denied  { mounton } for  pid=13476 comm="5" path="/tmp/buildah341221612/mnt/rootfs/sys/fs/cgroup/systemd" dev="cgroup" ino=1568 scontext=system_u:system_r:container_t:s0:c131,c995 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=0
```

**Comment by rhatdan** [comment]
Could you enable the cgroup boolean

setsebool -P container_manage_cgroup 1

Then see that fixes the issue.

**Comment by q384566678** [comment]
I verified it and it can run successfully. Thank you for your help.
