### ISSUE TITLE
Podman `play kube` errors out on podman-exported yaml

### ISSUE THREAD

**Issue by kofalt** [containers/libpod#3157]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This tickets represents the import woes to #2963's export woes.
I'm not yet convinced they are related.

**Steps to reproduce the issue:**

1. Similar to my comment here https://github.com/containers/libpod/issues/2963#issuecomment-493722755, take the exported Kube yaml from the [RH blog post](https://developers.redhat.com/blog/2019/01/29/podman-kubernetes-yaml/).
I have saved it as a [gist](https://gist.github.com/kofalt/ef08b519dd137eaf90d456ae186b895a) for convenience.

2. Observe that you are unable to import the YAML from the blog:

```
podman play kube blog.yml

Error: pod was given but no pod is specified: invalid argument
```

I was having the same problem importing my own YAML, and so reproduced it with only blog material to make the case clearer.

**Output of `podman version`:**

```
Version:            1.3.1-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by baude** [comment]
thanks for the well written defect, i appreciate the effort

**Comment by Fodoj** [comment]
Any update on this? Seems like play kube is unusable in 1.3.1

**Comment by mheon** [comment]
I think this is fixed upstream, and will be in 1.4.0 (which I'm releasing as we speak - https://github.com/containers/libpod/pull/3280

**Comment by Fodoj** [comment]
@mheon I tried with current master branch and it still doesn't work. New error is `Error: error running container create option: log driver must be set: invalid argument`

**Comment by haircommander** [comment]
hey @Fodoj can you PTAL at https://github.com/containers/libpod/pull/3283 and let me know if it fixes your play kube woes?

**Comment by mheon** [comment]
We need to improve testing here - we're breaking master repeatedly and not
catching it.

**Comment by Fodoj** [comment]
Re testing: I can only agree whole play kube feature needs to be better tested. I have different bugs in 1.3.1, 1.3.2 and now 1.4.0 versions, feels like there are no tests for this feature at all!

@haircommander don't have time to test it right now, I rolled back to 1.3.0, otherwise development of my app was blocked.

**Comment by kofalt** [comment]
Could this be reopened?

I'm afraid that on pod 1.4.0 from apt, using the same instructions above, I get a different error:

```bash
$ podman play kube blog.yml
Trying to pull quay.io/baude/demodb:latest...Getting image source signatures
Copying blob a3ed95caeb02 done

# ...

Copying blob a068a53bcb17 done
Writing manifest to image destination
Storing signatures
Error: error running container create option: log driver must be set: invalid argument
```

This is reminiscent of #3283, and the patch author actually mentions `play kube`:

> note: I considered fixing it on the play kube side, but instead opted for this

Let me know if anyone has trouble reproducing.

```bash
$ podman version
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Comment by haircommander** [comment]
Hey @kofalt this was fixed with podman 1.14.1 can you try that out?

**Comment by mheon** [comment]
I think you mixed up your versioning there - it's 1.4.1 :smile:

**Comment by mheon** [comment]
(We also have improved upstream testing for `play kube` so failures like this should be much less frequent from here on)

**Comment by kofalt** [comment]
Sounds good. I can confirm 1.4.1 solves the issue!
