### ISSUE TITLE
Relative path in ENTRYPOINT handled differently than Docker

### ISSUE THREAD

**Issue by mdempsky** [containers/libpod#4429]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman handles relative paths in ENTRYPOINT differently than docker does.

It also doesn't preserve empty WORKDIRs.

**Steps to reproduce the issue:**

Given this Dockerfile:

```
FROM alpine:latest
WORKDIR /app
RUN cp /sbin/apk apk-copy
ENTRYPOINT ["./apk-copy", "--version"]
```

Docker runs the container as I expect:

```
$ docker build -t bug-demo .
[...]
$ docker run --rm -it bug-demo
apk-tools 2.10.4, compiled for x86_64.
```

But podman does not:

```
$ podman build -t bug-demo .
[...]
$ podman run --rm -it bug-demo
Error: executable file not fonud in $PATH: No such file or directory: OCI runtime command not found error
```

Two related but more hypothetical discrepancies I noticed while trying to understand what was going on here:

1. The WORKDIR command in Docker always creates the directory, whereas `podman build` only seems to omit the directory if no files are copied into it. So this Dockerfile also works with docker, but not podman (it complains it can't cd into the non-existent /app directory):

       FROM alpine:latest
       WORKDIR /app
       ENTRYPOINT ["echo", "hello"]

2. It seems like podman is instead treating `./sh` as just `sh` and looking it up in $PATH. For example, this Dockerfile runs /bin/sh with podman (seemingly incorrectly), but fails with Docker (seemingly correctly, because /app/sh doesn't exist):

       FROM alpine:latest
       WORKDIR /app
       RUN touch foo  # workaround above podman issue
       ENTRYPOINT ["./sh"]

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.1-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 5e0eadedda9508810235ab878174dca1183f4013'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 6337355776
  MemTotal: 16654237696
  OCIRuntime:
    name: crun
    package: crun-0.10.2-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.2
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8396992512
  SwapTotal: 8396992512
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.3.7-301.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 16h 59m 14.69s (Approximately 0.67 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/matthew/.config/containers/storage.conf
  ContainerStore:
    number: 21
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/matthew/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 44
  RunRoot: /run/user/1000
  VolumePath: /home/matthew/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, X1 Carbon gen 6

**Comment by rhatdan** [comment]
This would be a Buildah bug, and should be moved over there, once it is fixed there it would get revendored into Podman

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by mdempsky** [comment]
The empty WORKDIR sounds like a buildah issue to me.

But I think the relative ENTRYPOINT is a podman issue, as `docker build` preserves the relative path in the container's ENTRYPOINT too:

```
$ docker image inspect bug-demo | grep -A4 WorkingDir
            "WorkingDir": "/app",
            "Entrypoint": [
                "./apk-copy",
                "--version"
            ],
--
            "WorkingDir": "/app",
            "Entrypoint": [
                "./apk-copy",
                "--version"
            ],
```

**Comment by mheon** [comment]
You're right - the entrypoint is definitely a Podman issue. I'll take that one.

**Comment by mheon** [comment]
@mdempsky I cannot reproduce on Podman 1.6.2 or Master, root or rootless - it's running `apt` exactly as you would expect it would.

**Comment by mdempsky** [comment]
@mheon To be clear, you're saying that this Dockerfile builds and runs with podman for you?

```
FROM alpine:latest
WORKDIR /app
RUN cp /sbin/apk apk-copy
ENTRYPOINT ["./apk-copy", "--version"]
```

I'm still able to reproduce the issue locally on Fedora 31 using podman/buildah installed via dnf.

I'm trying to figure out the best way to make this standalone reproducible, but I'm not that familiar with containers and currently running into issues running podman inside of docker/podman. Going to look into just using qemu to boot the Fedora 31 live DVD.

**Comment by mheon** [comment]
Yes - I built the Dockerfile you provided and ran it via `podman run -t -i --rm $IMAGE` and it successfully printed the output of `apt version`. In the debug logs, I can see the relative path is being used in the container command.

**Comment by mdempsky** [comment]
@mheon What OCI runtime are you using? Could it be an issue with crun specifically? Looking at strace -f output, I see a process trying to stat "/usr/bin/./apk-copy", etc., and it looks like it's from /usr/bin/crun.

**Comment by mheon** [comment]
I'm on `runc` - this definitely sounds like it could be a `crun` issue

@giuseppe PTAL

**Comment by mdempsky** [comment]
Oh, looks like containers/crun#133.

Should I just file the empty WORKDIR issue against buildah and close this issue then?

**Comment by mheon** [comment]
That sounds appropriate to me

**Comment by mdempsky** [comment]
Hm, actually the empty workdir problem goes away once I switch from `podman build` to `buildah bud`.

That is, given:

```
$ cat Dockerfile
FROM alpine:latest
WORKDIR /app
ENTRYPOINT ["echo", "hello"]
```

This works:

```
$ buildah bud -t demo -f Dockerfile
[...]
$ podman run --rm -it demo
hello
```
but this doesn't:

```
$ podman build -t demo -f Dockerfile
[...]
$ podman run --rm -it demo
Error: chdir: No such file or directory: OCI runtime command not found error
```

More curiously, `buildah version` reports 1.11.3, and containers/libpod@v1.6.2's go.mod pins github.com/containers/buildah v1.11.3.

**Comment by TomSweeneyRedHat** [comment]
Let's keep this one going.

**Comment by JAORMX** [comment]
Still struggling with this issue :(

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this PR.  I've tested today and this is working in Podman upstream.  I do see the issue in Podman v1.6.2.  I believe it's fixed in Podman v1.6.3 but I unfortunately don't have easy access to an rpm at the moment to test with.

**Comment by WarGloom** [comment]
fedora 32
podman-2.0.5-1.fc32.x86_64
exactly the same problem still exists
https://github.com/containers/podman/issues/4429#issuecomment-549588997
