### ISSUE TITLE
"E: Unable to locate package podman" ubuntu 19.10 server

### ISSUE THREAD

**Issue by medyagh** [containers/libpod#4769]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
installation docs

**Description**
The steps on website for installing podman on ubuntu doesn't work. https://podman.io/getting-started/installation

**Steps to reproduce the issue:**
I followed all the steps for ubuntu from the docs. 

```
sudo apt update
sudo apt install software-properties-common uidmap
sudo add-apt-repository ppa:projectatomic/ppa
sudo apt update
sudo apt install podman
```

**Describe the results you received:**

```
$ sudo apt -y install podman
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package podman
```

**Describe the results you expected:**

I expected to podman be installed.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```
Ubuntu 19.10 Server 
Baremetal

**Comment by medyagh** [comment]
it worth noting that it the PPA does not have the packages for ubuntu 19.10

![Screen Shot 2019-12-31 at 12 14 29 AM](https://user-images.githubusercontent.com/4564227/71614920-42c22d80-2b63-11ea-8e50-f3fe241f8d86.png)

I was able to force the PPA by adding a different version PPA to my sources.list

```
deb http://ppa.launchpad.net/projectatomic/ppa/ubuntu disco main

deb-src http://ppa.launchpad.net/projectatomic/ppa/ubuntu disco main
```
(I am on eoan)

**Comment by alitvak69** [comment]
You probably already know, but just in case, try this:

https://software.opensuse.org//download.html?project=devel%3Akubic%3Alibcontainers%3Astable&package=podman

**Comment by matihost** [comment]
Yes, and it seems final as  https://github.com/cri-o/cri-o/issues/2963#issuecomment-574478983 has been closed today and instructions in https://github.com/cri-o/cri-o/tree/release-1.16#installing-cri-o also apply to podman.

However for podman in  the new repository is unusable when docker is present in the system as well.

Issue: https://github.com/containers/libpod/issues/4747
The podman package (1.6.4) conflict with docker package:

```
dpkg: error processing archive /tmp/apt-dpkg-install-LhE9yQ/5-podman_1.6.4~2_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/docker-attach.1.gz', which is also in package docker.io 19.03.2-0ubuntu1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```

**Comment by alitvak69** [comment]
@lsm5 @jnovy Could you please take a look at #4747.  I am not running docker on the same boxes as podman anymore but it looks like number of devs do.

**Comment by rhatdan** [comment]
This was a screw up in packaging.  The podman-docker man pages ended up in the main podman package.  I believe @jnovy is fixing this.

**Comment by matihost** [comment]
The #4747 has been fixed and podman 1.7.0 install well on Ubuntu 19.10 now. Thank You.

**Comment by medyagh** [comment]
@rhatdan @matihost

I still have this issue on ubuntu 19.10 in google cloud

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
```

would you guys please test the documentation on the website

**Comment by lsm5** [comment]
@medyagh you're using the OBS repos and not the ppa, yes?
