### ISSUE TITLE
how to install newer  version of podman in centos or ubuntu ?

### ISSUE THREAD

**Issue by medyagh** [containers/libpod#5102]
I have been trying to do anything I can to install a newer version of podman ! I thought switching to centos would help !
but I cant get better than 1.4 from the package managers.

whats is the right way of installing latest version of podman on linux the instructipns on the website dont get me more than 1.4

I need that because there is a bug that podman cp , makes a new directory instead of copying files
https://github.com/containers/libpod/issues/3384

I also tried the instructions : Installing development versions of Podman
```
Ubuntu
The Kubic project provides RC/testing packages for Ubuntu 18.04, 19.04 and 19.10.

. /etc/os-release
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:testing/x${NAME}_${VERSION_ID}/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update -qq
sudo apt-get -qq -y install podman
$ sudo apt-get  install podman
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package podman
```

so I can't find any way to installer a relatively newer version of podman !

**Comment by rhatdan** [comment]
@lsm5 Please respond?

**Comment by adrianreber** [comment]
CRIU's CI using Podman also fails because it is no longer possible to install Podman from the stable kubic repository.

In the podman dependency tree there is the package containers-image but apt says:
```
# apt-get install podman containernetworking-plugins
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: containers-common (>= 0.1.40-9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
# apt-get install containers-image
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package containers-image is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'containers-image' has no installation candidate
```

**Comment by medyagh** [comment]
it worth noting the issue I had created a while ago and was closed is still happening (related)
https://github.com/containers/libpod/issues/4769#issuecomment-583018538

**Comment by lsm5** [comment]
i see this issue, working on it...

**Comment by lsm5** [comment]
Fixed.

Leaving the older packaging sources on OBS ended up confusing it so it didn't build anything. I will now rename packaging source files with a `.old` extension on update. /cc @alitvak69

Let me know if the issue still persists.

**Comment by adrianreber** [comment]
CRIU's CI can again install podman on Travis (Ubuntu 18.04).

**Comment by lsm5** [comment]
@medyagh RE: centos, podman 1.8.0 has been built for centos 7 and 8 but I'm fixing some dependencies for centos8 atm. Will update docs once it's done.

**Comment by medyagh** [comment]
@lsm5 thank you for such a fast response, I will try later tonight, is the documentaiton up to date ? if i follow line by line will it get me something working on centos ?

and is it also fixed on ubuntu ?

**Comment by lsm5** [comment]
ubuntu works with the current docs.

docs for centos7 aren't updated yet, but you can do this as root to install podman:
```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo
yum install podman
```

still working on solving dependency issues for centos8.

**Comment by medyagh** [comment]
@lsm5  I confirm doing this works on centos 7:
run as root:
```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_7/devel:kubic:libcontainers:stable.repo
yum install podman
```

```
[root@podmanexp yum.repos.d]# podman version
Version:            1.8.0-rc1
RemoteAPI Version:  1
Go Version:         go1.13.3
OS/Arch:            linux/amd64
```


@lsm5 can you plz double check the ubuntu instructions ? last night I tried it on two different ubuntu versions 19.10 and 18.04 on google cloud VMs and they didnt work to install podman if followed instructions from site

**Comment by medyagh** [comment]
on debian 10 I could get podman 1.7 
but on centos 7 I get 1.8

1.8 has a bug in it

it would be nice to have option to install whatever version u wish or be consistant across all platforms.

**Comment by medyagh** [comment]
@lsm5 I just tried the ubuntu instructions on the site

. /etc/os-release
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -q https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | sudo apt-key add -
sudo apt-key add - < Release.key
sudo apt-get update -qq
sudo apt-get -qq -y install podman"
"


this line gives error : sudo apt-key add - < Release.key
I had to remove that line to make it work for minikube https://github.com/kubernetes/minikube/pull/6515/files#diff-90829e76e906f1c73140c7ded7e1b268R151

**Comment by lsm5** [comment]
> @lsm5 can you plz double check the ubuntu instructions ? last night I tried it on two different ubuntu versions 19.10 and 18.04 on google cloud VMs and they didnt work to install podman if followed instructions from site'
> 
> is there a way I could install 1.7?

The instructions mentioned at https://podman.io/getting-started/installation worked for me on ubuntu 19.10. Could you please post the exact error that you see?

> it would be nice to have option to install whatever version u wish or be consistant across all platforms.

I think I can ensure version consistency for all distros, but picking any version you want (I'm told) isn't doable with OBS.

**Comment by lsm5** [comment]
ah yup, that extra `apt-key add` needs to be removed. I'll PR for that, thanks

**Comment by lsm5** [comment]
@medyagh I'll be removing the podman 1.8.0 rpm from the stable repo and building a new 1.7.0 (assuming it lets me), so, brace for impact

**Comment by lsm5** [comment]
@medyagh btw, have you reported the bug you found in 1.8 already? Cause 1.8.0 got released just now, and I'd prefer to send that to all distros

**Comment by johnmmcgee** [comment]
would also like 1.7, if available for centos8.

**Comment by vrothberg** [comment]
Looks like the initial issue is fixed, closing.

**Comment by johnmmcgee** [comment]
The centos 8 repo is still not working.   I have it enabled and it will not pull the packages when attempting a dnf update.

**Comment by vrothberg** [comment]
The package is definitely there (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/x86_64/) but I also fail to install it:
```
[root@a1bf4120468b yum.repos.d]# dnf install podman-1.8.0-14.1.el8.x86_64
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:04:54 ago on Thu Feb 13 13:45:33 2020.
No match for argument: podman-1.8.0-14.1.el8.x86_64
Error: Unable to find a match: podman-1.8.0-14.1.el8.x86_64
```

It sees the aarch64 one though. @lsm5 PTAL.

**Comment by lsm5** [comment]
mind retrying please? Also, see https://github.com/containers/podman.io/pull/201

**Comment by johnmmcgee** [comment]
Same issue as before.  I am unable to install any items from that repo.

**Comment by lsm5** [comment]
> Same issue as before. I am unable to install any items from that repo.

could you post all the commands you used along with the output messages please?

**Comment by johnmmcgee** [comment]
Hello,

So i followed the instructions, per the website.  Here is an output to show you what is available in dnf.

`[root@bender ~]# cat /etc/yum.repos.d/devel\:kubic\:libcontainers\:stable.repo
[devel_kubic_libcontainers_stable]
name=Stable Releases of Upstream github.com/containers packages (CentOS_8)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/repodata/repomd.xml.key
enabled=1
[root@bender ~]# dnf --showduplicates list podman
Last metadata expiration check: 0:01:26 ago on Thu 13 Feb 2020 06:28:38 PM EST.
Installed Packages
podman.x86_64                                                   1.6.4-2.module_el8.1.0+272+3e64ee36                                                   @Stream-AppStream
Available Packages
podman.x86_64                                                   1.6.4-2.module_el8.1.0+272+3e64ee36                                                   AppStream
podman.aarch64                                                  1.8.0-14.1.el8                                                                        devel_kubic_libcontainers_stable
podman.src                                                      1.8.0-14.1.el8                                                                        devel_kubic_libcontainers_stable
[root@bender ~]#`

**Comment by lsm5** [comment]
@johnmmcgee did you disable the container-tools module?

```
sudo dnf module disable container-tools
```

**Comment by bbros-dev** [comment]
We're hitting errors installing on Ubuntu again, after having had issues in the past too.  We don't have time to waste on these issues.  Buold infrastructure should just work and not be broken by packages making new releases.

@lsm5 and @rhatdan: Please remove references to Ubuntu installs other than Ubuntu upstream, and work with upstream Ubuntu to get podman released more often.

We pushed a Podman howto article as part of Vultr's documentation program, and are embarrassed by these breakages.
We won't make the same mistake again.

For other's, Podman installs from the podman project instructions has repeatedly caused us headaches: Use podman from upstream Ubuntu repo's or don't bother and stick with docker.  
It has now, for us, reached the point where podman's value add is not enough to justify the additional time.

Ack, this is purely an issue on Ubuntu, and using podman versions not released by Ubuntu.
