### ISSUE TITLE
podman remote clients for windows and mac links are broken in readme file

### ISSUE THREAD

**Issue by praveenkumar** [containers/libpod#6033]
podman-remote latest clients links which are part of readme are broken and there is no way to download those clients from the mentioned urls.

**Comment by mheon** [comment]
We've started adding the binaries to the individual Github releases (e.g. the [v1.9.1](https://github.com/containers/libpod/releases/tag/v1.9.1) release). We should update the readme to reflect that.

**Comment by praveenkumar** [comment]
@mheon thanks but it doesn't have for linux binary, any plan to add that or that is complete depend on distribution way of providing?

**Comment by baude** [comment]
@praveenkumar given that the linux client is not truely static (distributions will need different binaries), how would you recommend we do this (if we could)?

**Comment by rhatdan** [comment]
If we make a static binary, it should only be podman-remote not full podman.

**Comment by praveenkumar** [comment]
@baude @rhatdan I am right now only interested in the podman-remote binary not full podman since on the release page we are only listing the remote clients and those are static binary if I am not mistaken?

**Comment by praveenkumar** [comment]
Another thing I notice here on https://github.com/containers/libpod/releases/tag/v1.9.1 page there is one zip file which name as podman-remote for windows and then there is msi for windows  but it is just named as podman, shouldn't that would also podman-remote ? Also there is no tarball of podman-remote for macOS/Linux on the release page.

**Comment by baude** [comment]
No, that was a special request but a agroup we work with.

**Comment by rhatdan** [comment]
Podman exutables on MAC and Windows, should be called Podman NOT podman-remote.  We should only use/install the `podman-remote` executable on Linux boxes, to eliminate confusion with the full featured `podman` command.

**Comment by afbjorklund** [comment]
I installed "podman-remote" in a special PATH (as "podman"), so that I can troubleshoot podman-remote issues also on Linux... The alternative would have been to just call it `podman-remote` everywhere.

**Comment by nimula** [comment]
Is there any place can find the tarball file of podman for macOS?

**Comment by afbjorklund** [comment]
> Is there any place can find the tarball file of podman for macOS?

I think it is available in Homebrew ? `brew cask install podman`

**Comment by nimula** [comment]
> 
> 
> > Is there any place can find the tarball file of podman for macOS?
> 
> I think it is available in Homebrew ? `brew cask install podman`

The Homebrew version stays at 1.6.1-dev, I hope to find a newer version.

**Comment by rhatdan** [comment]
They should be available from here.
https://github.com/containers/libpod/releases/tag/v1.9.2

**Comment by afbjorklund** [comment]
The mac binary seems to be missing yet, maybe it is upcoming ?
(there is windows and static and .msi, but no darwin or mac installer)

Was there any volunteers for adding podman to homebrew proper ?
(to build it from source code, rather than the current binary "cask")

**Comment by afbjorklund** [comment]
I'm not sure if you are missing all that much by going with 1.6 ?

It's only the client, most of the improvements happen server-side

**Comment by nimula** [comment]
Thanks, I will try the homebrew version.

**Comment by rhatdan** [comment]
@mheon Why is there no mac client on https://github.com/containers/libpod/releases/tag/v1.9.2?

**Comment by mheon** [comment]
Nobody told me to build one, so I didn't - I assume we do want one?

**Comment by rhatdan** [comment]
We want a MAC Version yes, primarily for CRC.

**Comment by mheon** [comment]
Fixed now

**Comment by sjanssen15** [comment]
Link for WIndows is still broken on https://podman.io/getting-started/installation

**Comment by rhatdan** [comment]
Sorry about that, I fixed it.  I accidently marked a pre-release as a release.
