### ISSUE TITLE
Issue starting rootless container with systemd

### ISSUE THREAD

**Issue by TheEagle13** [containers/libpod#6422]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When attempting to control autostart of a rootless container with systemd, it errors out with a message of 
`error creating libpod runtime: database libpod temporary files directory (tmpdir) \"/run/user/1000/run\" does not match our libpod temporary files directory (tmpdir) \"/var/run/libpod\": database  configuration mismatch"`

**Steps to reproduce the issue:**

1. Create a rootless container

2. podman generate systemd container > /lib/systemd/system/pod-container.service

3. sudo systemctl start pod-container.service

**Describe the results you received:**
Service fails to start.

[systemctl_status.txt](https://github.com/containers/libpod/files/4697950/systemctl_status.txt)
[journalctl.txt](https://github.com/containers/libpod/files/4697923/journalctl.txt)

**Describe the results you expected:**
The container should start normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 33da5ef83bf2abc7965fc37980a49d02fdb71826'
  cpus: 24
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: Dewey.netriscs.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.13-300.fc32.x86_64
  memFree: 870588416
  memTotal: 33642397696
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 16888360960
  swapTotal: 16890458112
  uptime: 52h 14m 42.65s (Approximately 2.17 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 5
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 7
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.1-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Server Running Fedora 32

**Comment by mheon** [comment]
Can you upgrade to Podman v1.9.2 or higher and re-try? We've already fixed this one.

I don't know if v1.9.2 every made it to stable in Fedora, but v1.9.3 should be in updates-testing - `dnf --enablerepo=updates-testing upgrade podman` should grab it.

**Comment by TheEagle13** [comment]
Sorry for not replying Immediately, but this is NOT resolved.
I tried with Podman 1.9.2, same issue, then I upgraded to the testing 1.9.3, and the issue still persists. Please re-open.

**Comment by TheEagle13** [comment]
It does seem to be throwing a different error now though:
`Error: unable to find container 952a8f7a8a602a83ca192c4a608da95412e5a9f6ff4c5571bfed5fe2d410ff6b: no container with name or ID 952a8f7a8a602a83ca192c4a608da95412e5a9f6ff4c5571bfed5fe2d410ff6b found: no such container`

**Comment by vrothberg** [comment]
Root cannot see rootless containers as the storage paths differ. When running rootless containers via systemd, the unit files must be installed at the correct path (see https://github.com/containers/libpod/blob/master/docs/source/markdown/podman-generate-systemd.1.md#installation-of-generated-systemd-unit-files) and be started via `systemctl **--user**`.

**Comment by TheEagle13** [comment]
> Root cannot see rootless containers as the storage paths differ. When running rootless containers via systemd, the unit files must be installed at the correct path (see https://github.com/containers/libpod/blob/master/docs/source/markdown/podman-generate-systemd.1.md#installation-of-generated-systemd-unit-files) and be started via `systemctl **--user**`.

The link your reference seems to contradict your statement.

`Note: Coping unit files to /usr/lib/systemd/system and enabling it marks the unit file to be automatically started at boot. And smillarly, coping a unit file to $HOME/.config/systemd/user and enabling it marks the unit file to be automatically started on user login`

I need these containers to start at boot, so I place the config in the appropriate path. How else am I supposed to securely start non root containers at boot?

**Comment by vrothberg** [comment]
The problem in your specific example is:

> podman generate systemd container > /lib/systemd/system/pod-container.service

The generated .service file _starts_ an existing container which is in the rootless storage. Hence, you cannot use it as another user (even root) which ultimately leads to 

> Error: unable to find container 952a8f7a8a602a83ca192c4a608da95412e5a9f6ff4c5571bfed5fe2d410ff6b: no container with name or ID 952a8f7a8a602a83ca192c4a608da95412e5a9f6ff4c5571bfed5fe2d410ff6b found: no such container

... as root container storage does not know this container.

Running rootless container in system (i.e., root) services can be done by user the `User/Group=...` attributes of systemd. An example can be found in the following issue: https://github.com/containers/libpod/issues/5572#issuecomment-626727010

However, there are _many_ things that could go wrong and we don't yet officially support it. But we're working together with the systemd folks to find a solution.

**Comment by vrothberg** [comment]
I recommend using `podman generate systemd --new` which will generate services that create _new_ container in contrast to the default services which start existing containers.

**Comment by TheEagle13** [comment]
Will the ` podman generate systemd --new` generated file in /lib/systemd start as root or as user? The whole point is to run the containers as non-root.

I will try your other suggestion of supplying the user/group to the systemd file. Maybe this should be reopened as a feature enhancment then? Surely I'm not the only one who would like to see rootless containers auto start at boot up.

**Comment by vrothberg** [comment]
> Will the podman generate systemd --new generated file in /lib/systemd start as root or as user? The whole point is to run the containers as non-root.

They will start with all users. But note that you want to run rootless containers as root (via a root system service).

> I will try your other suggestion of supplying the user/group to the systemd file. 

Please note that we don't support that yet (see #5572).

> Maybe this should be reopened as a feature enhancment then? Surely I'm not the only one who would like to see rootless containers auto start at boot up.

This is already supported. You need to enable lingering (`# loginctl enable-linger username`) for your user and enable the _non-root_ service via `$ systemctl --user $service`.

**Comment by TheEagle13** [comment]
`Systemctl - - user $service` does NOT enable them at boot, it only enables them at login. Since this is a server, if there happens to be A failure where it needs to reboot, they will not start until the user logs in. So it appears to not be supported yet.

**Comment by vrothberg** [comment]
Again. Your scenario is supported but you need to enable lingering for your user. I just created a clean Fedora 32 VM and did the following steps:

1. Create a .service file and copy it to `$USER/.config/systemd/user`.
2. Load and enable the service via `systemctl --user ...`
3. Enable lingering via: `# loginctl enable-linger username`
4. Reboot the system.
5. Login as root (not as the user) and check if the service is running (and it is running).

Step 3 is the crucial part of getting the services to start at boot (even for non root users).

**Comment by TheEagle13** [comment]
Sorry for dragging this out. I kept getting confused by the constant statement that it wasn't supported. (And it was early)
